// import nanoid from 'nanoid';

export { default as copy } from 'copy-to-clipboard';
export { default as cloneDeep } from 'lodash/cloneDeep';
export { default as debounce } from 'lodash/debounce';
export { default as isEmpty } from 'lodash/isEmpty';
export { default as isEqual } from 'lodash/isEqual';
export { default as isObject } from 'lodash/isObject';
export { default as throttle } from 'lodash/throttle';
export { default as aesDecrypt } from './aesDecrypt';
export { default as aesEncrypt } from './aesEncrpyt';
export { default as AudioController } from './audio/audio';
export type { AudioOptions } from './audio/audio';
export { default as Request } from './axios/axios';
export type { RequestOption } from './axios/axios';
export { default as base64 } from './base64';
export { default as clientRect } from './clientRect/clientRect';
export { default as cookie } from './cookie/cookie';
export { default as getFileId } from './createFileHash';
export { default as debug } from './debug/debug';
export { default as download } from './download';
export { off, on } from './eventListener/eventListener';
export {
  EventEmitter,
  default as eventemitter,
} from './eventemitter/eventemitter';
export { default as fileOpts } from './file/file';
export { formatDiscount, formatMoney } from './format/format';
export { default as formatPercent } from './formatPercent';
export { default as formatString } from './formatString';
export { default as fullscreen } from './fullscreen/fullscreen';
export { default as getImgSize, type ImgSizeData } from './getImgSize';
export { default as IFrame } from './iframe';
export { injectionScript, injectionStyle } from './injection/injection';
export type { ScriptOption, styleOption } from './injection/injection';
export { default as isNumber } from './isNumber';
export { default as joinCss } from './joinCss/joinCss';
export { default as loadExternal } from './loadExternal';
export { default as modifyImgColor } from './modifyImgColor';
export { default as obj2url } from './obj2url';
export { default as openTab } from './openTab/openTab';
export { default as registerPageHidden } from './pageHidden';
export { default as regexs } from './regex/regex';
export { default as ResizeListener } from './resizeObserver/resizeObserver';
export { default as safeJson } from './safeJson/safeJson';
export { default as ScrollIntersection } from './scrollIntersection';
export { default as sleep } from './sleep/sleep';
export { default as smoothScrollTo } from './smoothScrollTo/smoothScrollTo';
export type { SmoothScrollToOptions } from './smoothScrollTo/smoothScrollTo';
export { default as Storage } from './storage/storage';
export { default as timestamp } from './timestamp/timestamp';
export { getParameterByName } from './url/url';
export { default as uuid } from './uuid/uuid';
